Force exit failure on nonzero exit status

diff --git a/.github/workflows/optimism-ci.yaml b/.github/workflows/optimism-ci.yaml
--- a/.github/workflows/optimism-ci.yaml
+++ b/.github/workflows/optimism-ci.yaml
@@ -71,23 +71,27 @@ jobs:
         shell: bash
         run: |
           pushd optimism/packages/contracts-bedrock > /dev/null
-          kaas-cli --vault ${{ secrets.OPTIMISM_VAULT }} --token ${{ secrets.OPTIMISM_TOKEN }} download -d kout-proofs/
+          kaas-cli --vault ${{ secrets.OPTIMISM_VAULT }} --token ${{ secrets.OPTIMISM_TOKEN }} download -d ./kout-proofs/
   
       - name: 'Run Kontrol'
         shell: bash
         run: |
-          set -xeu pipefail
+          set -xeou pipefail
           # Run the following in the running docker container
           pushd optimism/packages/contracts-bedrock > /dev/null
           # Need to checkout submodules, GH action doesn't do this properly. 
           git submodule update --init --recursive
-          find . -name "run-kontrol.sh" -type f -exec {} ${{ github.event.inputs.extra_args }} \;
+          find . -name "run-kontrol.sh" -type f -exec {} ${{ github.event.inputs.extra_args }} \; 
+          if $? -ne 0; then
+            echo "Kontrol failed"
+            exit 1
+          fi
 
       - name: 'KCFG Upload Results'
         shell: bash
         run: |
           pushd optimism/packages/contracts-bedrock > /dev/null
-          kaas-cli --vault ${{ secrets.OPTIMISM_VAULT }} --token ${{ secrets.OPTIMISM_TOKEN }} upload -d kout-proofs/
+          kaas-cli --vault ${{ secrets.OPTIMISM_VAULT }} --token ${{ secrets.OPTIMISM_TOKEN }} upload -d ./kout-proofs/
       
       - name: 'Upload KCFG Results to Summary'
         if: always()
